### ISSUE TITLE
Error message when linking to a superroute

### ISSUE THREAD

**Issue by DD1GJ** [waymarkedtrails/waymarked-trails-site#315]
https://hiking.waymarkedtrails.org/#route?id=9507544 generates the message "Keine Einzelheiten für dieses Objekt gefunden." (No details found for this object.) It worked perfectly two weeks earlier.

The message also appears when clicking on a section of a route as soon as it is contained in several hiking relations, e.g. https://www.openstreetmap.org/way/684674322

**Comment by lonvia** [comment]
Fixed in 380157ea555068e28d94814e99cc66b8e5ae1438.

**Comment by DD1GJ** [comment]
The link works now, but after a click on the above way, the message still appears.

**Comment by lonvia** [comment]
Hopefully fixed all the places now.
